### ISSUE TITLE
UI for Anonymous Topic Feature (Frontend)

### ISSUE THREAD

**Issue by elliay** [CMU-313/nodebb-f24-dry-cleaners#10]
Description: Add a toggle to the UI of topic creation that leads to changing the anonymity status of the poster for that specific topic.

Effort: Medium-Low

Dependencies: Should be implemented in a similar way as the UI for Anonymous Topic Feature #8 

Acceptance Criteria:

This toggle should modify the status of anonymity parameter of topic creation during the creation of a topic.
This functionality of this toggle should be easy for the user to identify and understand.

**Comment by yiyao625** [comment]
We decided to not implement this during Sprint 2 from our experience in Sprint 1 which gave us a better understanding of time estimates.
