### ISSUE TITLE
UI for indicating unread messages (Frontend)

### ISSUE THREAD

**Issue by reemhashir1** [CMU-313/nodebb-f24-dry-cleaners#11]

**Comment by reemhashir1** [comment]
Description: As an instructor, I want to easily identify which posts that havent been read yet to provide the students with timely reply.

Effort: Medium

Dependencies: Should be implemented in a similar way as the Sorting and filtering unread messages to the main dashboard (Backend) #12


Acceptance Criteria:

Unread Post Indicator:

Unread posts should be clearly marked with an icon next to the post.

**Comment by yiyao625** [comment]
We decided to not implement this during Sprint 2 from our experience in Sprint 1 which gave us a better understanding of time estimates.
