### ISSUE TITLE
Sorting and filtering unread messages to the main dashboard (Backend)

### ISSUE THREAD

**Issue by reemhashir1** [CMU-313/nodebb-f24-dry-cleaners#12]

**Comment by reemhashir1** [comment]
Description: As an instructor, I want to easily identify which posts that havent been read yet to provide the students with timely reply.

Effort: Medium

Dependencies: Should be implemented in a similar way as UI for indicating unread messages (Frontend) #11


Acceptance Criteria:

Real-Time Updates: The interface must update in real-time when a post is read, reflecting the changes of a post being read already.

**Comment by yiyao625** [comment]
We decided to not implement this during Sprint 2 from our experience in Sprint 1 which gave us a better understanding of time estimates.
