### ISSUE TITLE
Anonymous Post Feature (Backend)

### ISSUE THREAD

**Issue by elliay** [CMU-313/nodebb-f24-dry-cleaners#7]
Description: Implement another parameter when the user creates a post to signal the anonymity status of the poster.

Effort: Medium

Dependencies: Should be implemented in a similar way to the Anonymous Topic Feature (Backend) #9 

Acceptance Criteria:

Anonymity of the poster should be one of the parameters during post creation
Modification of this parameter should be accessible from the frontend

**Comment by yiyao625** [comment]
We decided to not implement this during Sprint 2 from our experience in Sprint 1 which gave us a better understanding of time estimates.
