### ISSUE TITLE
UI for Anonymous Post Feature (Frontend)

### ISSUE THREAD

**Issue by elliay** [CMU-313/nodebb-f24-dry-cleaners#8]
Description: Add a toggle to the UI of post creation that leads to changing the anonymity status of the poster for that specific post.

Effort: Medium-Low

Dependencies: Should be implemented in a similar way as the UI for Anonymous Topic Feature #10 

Acceptance Criteria:

This toggle should modify the status of anonymity parameter of post creation during the creation of a post.
This functionality of this toggle should be easy for the user to identify and understand.

**Comment by yiyao625** [comment]
We decided to not implement this during Sprint 2 from our experience in Sprint 1 which gave us a better understanding of time estimates.

**Comment by yiyao625** [comment]
We decided to not implement this during Sprint 2 from our experience in Sprint 1 which gave us a better understanding of time estimates.
